
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always


spring: 
  datasource: 
    url: jdbc:mysql://localhost:3306/Acmeplex?useSSL=false&serverTimezone=America/Edmonton&createTableIfNotExists=true&allowPublicKeyRetrieval=true
    username: root 
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: Acmeplex
#   datasource:
#     url: ${MYSQL_DB_URL}
#     username: ${MYSQL_DB_USERNAME}
#     password: ${MYSQL_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: meluxmeme@gmail.com
    password: megplbqczqqrmnnr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000



logging:
  level:
    org.springframework.security: DEBUG
    root: INFO
    org.springframework.web: DEBUG
    org.springframework: DEBUG  # Optionally enable logging for other Spring packages
    com.yourpackage: DEBUG 

jwt:
  secret: 404D635166546A576E5A7234753778214125442A472D4B6150645267556B5870
  expiration: 86400000 # 24 hours in milliseconds

stripe:
  api:
    key: sk_test_51QNrf6EN5RfB81n8y68FX08ZqjxpMAKcVORyttoRodYPeVWZfwjoogDhSOWnAKEfZW4DamJeoWlsJgWJgRbbCVcD00haA3eZPg
    public-key: pk_test_51QNrf6EN5RfB81n8KfmB4d7WbCfXCHZt6fAMCggqvXjKo2irMoAHFGaTHKeAETb4w98F9CpANd44s6Lrz23u87UD00shIXk2Uy
    secret: whsec_5a77522b04760d992978cab6144b0d040146bb1f92699e72a634c538081c08fd


    # key: ${STRIPE_API_KEY}
    # public-key: ${STRIPE_PUBLIC_KEY}