server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/Acmeplex?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

  mail:
    host: localhost
    port: 3306
    username: root
    password: root

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
logging:
  level:
    org.springframework.security: DEBUG
      