server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always


spring: 
  config:
    import: "optional:file:.env[.properties]"
  datasource: 
    url: ${MYSQL_DB_URL}
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: Acmeplex
#   datasource:
#     url: ${MYSQL_DB_URL}
#     username: ${MYSQL_DB_USERNAME}
#     password: ${MYSQL_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: meluxmeme@gmail.com
    password: megplbqczqqrmnnr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

logging:
  level:
    org.springframework.security: DEBUG
    root: INFO
    org.springframework.web: DEBUG
    org.springframework: DEBUG  # Optionally enable logging for other Spring packages
    com.yourpackage: DEBUG 

jwt:
  secret: ${JWT-SECRET}
  expiration: 86400000 # 24 hours in milliseconds

stripe:
  api:
    secret-key: ${STRIPE_SECRET_KEY}
    public-key: ${STRIPE_PUBLIC_KEY}
  webhook:
    secret: ${STRIPE-WEBHOOK-SECRET}

    # key: ${STRIPE_API_KEY}
    # public-key: ${STRIPE_PUBLIC_KEY}